### PR TITLE
[CLOSED] Editing gametext

### PR DESCRIPTION
**Pull request by TheDrawingCoder-Gamer**

### CODE REVIEW

**Comment by TheDrawingCoder-Gamer** [comment]
are you even allowed to make pull requests? :p

**Comment by Godson777** [comment]
Pull requests are fine, as long as they don't edit the games.txt (mostly due to it being configurable outside of github) and actually contribute something to the development.

**Comment by TheDrawingCoder-Gamer** [comment]
Ok, but i don't really know how to code, so i'm sorry, idk how to remove this, but i'm going to try.

**Comment by TheDrawingCoder-Gamer** [comment]
But how is it configurable out of github? how do i do that or can you only do it?

**Comment by Godson777** [comment]
The original version of KekBot that's currently public only allows me to add games to the list, if you were to host your own bot with KekBot's code, you can make it allow you to add games to that bot.

**Comment by TheDrawingCoder-Gamer** [comment]
How could i host a bot like that?
im completly new at this as you see.

**Comment by Godson777** [comment]
You'd have to have an understanding of the Discord API and some Java knowledge to hook all this code into a discord bot

**Comment by TheDrawingCoder-Gamer** [comment]
Well, its not that important.

**Comment by TheDrawingCoder-Gamer** [comment]
Can I just fork this? :P

**Comment by TheDrawingCoder-Gamer** [comment]
where is ur app.py i don't understand anything and will this not stay up if i don't have a server
so many questions.

**Comment by Godson777** [comment]
Wut.

I said **Java**, not **Python**. App.py only applies to Python-based programs, KekBot was built in Java, which is more complicated.

**Comment by TheDrawingCoder-Gamer** [comment]
ok. i should just stop. :P

**Comment by TheDrawingCoder-Gamer** [comment]
i assume you're using JDA, but you might be using Discord4j, Idk what api you're using.

**Comment by TheDrawingCoder-Gamer** [comment]
o it says on it it says your using JDA :p

**Comment by Diamondman121314** [comment]
Godson is using JDA for KekBot.

**Comment by Diamondman121314** [comment]
Oh. I was too late.

**Comment by TheDrawingCoder-Gamer** [comment]
:P

**Comment by TheDrawingCoder-Gamer** [comment]
i just can't find the things i need to change, do you know what i need to change to make it work?

**Comment by Diamondman121314** [comment]
I have no idea on how to run the bot. Sorry. :E

**Comment by TheDrawingCoder-Gamer** [comment]
it's fine, I just can't understand the API

**Pull request closed without merging**
